export default {
  analytics: {
    FAILED_SIGN_IN: 'FAILED_SIGN_IN',
    FAILED_SIGN_UP: 'FAILED_SIGN_UP',
    FAILED_UPDATE_PROFILE: 'FAILED_UPDATE_PROFILE',
    FAILED_GET_USER: 'FAILED_GET_USER',
    FAILED_CONFIRM_ACCOUNT: 'FAILED_CONFIRM_ACCOUNT',
  },
}
